print("Think of a number between 1 to 10...")
time.sleep(2)
print("Multiply it by 9...")
time.sleep(2)
print("Add the digits of the result...")
time.sleep(2)
print("Subtract 5 from that number...")
time.sleep(2)
print("Match it to a letter (1=A, 2=B, ..., 26=Z)")
time.sleep(2)
print("Now think of a country that starts with that letter.")
time.sleep(3)
print("I guess... *Denmark 🇩🇰*")